### ISSUE TITLE
training with larger batch size fails

### ISSUE THREAD

**Issue by zchrissirhcz** [BinWang-shu/pytorch_hed#2]
Thank you for sharing this code.

Now I would like to train with larger batch size, by typing `python train.py --batchSize 2`, but meet this error:

```
Traceback (most recent call last):
  File "train.py", line 143, in <module>
    for i, image in enumerate(train_loader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 109, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 91, in default_collate
    return torch.stack(batch, 0, out=out)
  File "/usr/local/lib/python2.7/dist-packages/torch/functional.py", line 66, in stack
    return torch.cat(inputs, dim, out=out)
RuntimeError: inconsistent tensor sizes at /pytorch/torch/lib/TH/generic/THTensorMath.c:2709
```

Do you have any suggestions?

**Comment by BinWang-shu** [comment]
I suggest that you can write a function to input dataset in yourself instead of using dataloader from pytorch. I also find this error.

**Comment by zchrissirhcz** [comment]
Thanks for your fast response. I'll have a try.
